# Generated by Django 2.2.16 on 2021-11-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('promo_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('discount_amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('outlet_savings', models.IntegerField()),
            ],
            options={
                'db_table': 'outlet',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=25)),
                ('no_of_seats', models.IntegerField()),
                ('ac', models.BooleanField()),
                ('vehicle_status', models.CharField(max_length=25)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_access.Outlet')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('vehicle_taken_date', models.DateField()),
                ('expected_return_date', models.DateField()),
                ('advance', models.IntegerField()),
                ('reservation_status', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_access.Customer')),
                ('emp', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_access.Employee')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_access.Outlet')),
                ('plt_no', models.ForeignKey(default='car sold/no more', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_access.Vehicle')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('taken_date', models.DateField()),
                ('return_date', models.DateField()),
                ('no_of_days', models.IntegerField()),
                ('tax_amt', models.IntegerField(default=10)),
                ('total_amt', models.IntegerField()),
                ('refund', models.IntegerField()),
                ('customer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_access.Customer')),
                ('plt_no', models.ForeignKey(default='car sold/no more', on_delete=django.db.models.deletion.SET_DEFAULT, to='customer_access.Vehicle')),
                ('reservation', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='customer_access.Reservation', unique=True)),
            ],
            options={
                'db_table': 'rent',
            },
        ),
        migrations.CreateModel(
            name='Outlet_Contact',
            fields=[
                ('outlet_phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('outlet_mail', models.EmailField(max_length=254)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_access.Outlet')),
            ],
            options={
                'db_table': 'outlet_contact',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_access.Outlet'),
        ),
    ]
