# Generated by Django 2.2.16 on 2021-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_access', '0002_auto_20211122_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
