# Generated by Django 2.2.16 on 2021-11-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_access', '0003_auto_20211122_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='cost_per_day',
            field=models.IntegerField(default=1000),
        ),
    ]
